// <auto-generated />
using EditoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EditoreAPI.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    [Migration("20241209094535_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EditoreAPI.Model.Editore", b =>
                {
                    b.Property<int>("EditoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EditoreId"));

                    b.Property<string>("NomeEditore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("citta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EditoreId");

                    b.ToTable("Editori");
                });

            modelBuilder.Entity("EditoreAPI.Model.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("EditoreId")
                        .HasColumnType("int");

                    b.Property<double>("Prezzo")
                        .HasColumnType("double");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("numeroPagine")
                        .HasColumnType("int");

                    b.HasKey("LibroId");

                    b.HasIndex("EditoreId");

                    b.ToTable("Libri");
                });

            modelBuilder.Entity("EditoreAPI.Model.Libro", b =>
                {
                    b.HasOne("EditoreAPI.Model.Editore", "Editore")
                        .WithMany("Libri")
                        .HasForeignKey("EditoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editore");
                });

            modelBuilder.Entity("EditoreAPI.Model.Editore", b =>
                {
                    b.Navigation("Libri");
                });
#pragma warning restore 612, 618
        }
    }
}
